version: "3.7"
services:
  dev_db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: abb123
      POSTGRES_USER: postgres
      POSTGRES_DB: abb
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql