export const DELETED_PRODUCT_FAIL_MESSAGE = 'DELETED PRODUCT FAIL';
export const DELETED_SKU_FAIL_MESSAGE = 'DELETE SKU FAIL';
export const FETCH_ALL_PRODUCT_FAIL = 'CAN NOT GET LIST PRODUCT';
export const FETCH_ALL_SKU_FAIL = 'CAN NOT GET LIST SKU';
export const LOGIN_FAIL = 'LOGIN FAILED';
export const DELETE_SUCCESSFULLY = 'DELETE SUCCESSFULLY'
export const SAVE_PRODUCT_SUCCESS_MESSAGE = 'SAVE PRODUCT SUCCESSFULY'
export const SAVE_PRODUCT_FAIL_MESSAGE = 'SAVE PRODUCT FAIL'